// Mocks generated by Mockito 5.4.6 from annotations
// in flowery/test/feature/profile/data/repository/profile_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flowery/feature/profile/api/api/profile_api_client.dart' as _i4;
import 'package:flowery/feature/profile/data/models/profile_response_model.dart'
    as _i2;
import 'package:flowery/feature/profile/domain/entities/profile_entity.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProfileResponseModel_0 extends _i1.SmartFake
    implements _i2.ProfileResponseModel {
  _FakeProfileResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileUserModel_1 extends _i1.SmartFake
    implements _i2.ProfileUserModel {
  _FakeProfileUserModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileEntity_2 extends _i1.SmartFake implements _i3.ProfileEntity {
  _FakeProfileEntity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileApiClient extends _i1.Mock implements _i4.ProfileApiClient {
  MockProfileApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ProfileResponseModel> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i5.Future<_i2.ProfileResponseModel>.value(
              _FakeProfileResponseModel_0(
                this,
                Invocation.method(#getProfile, []),
              ),
            ),
          )
          as _i5.Future<_i2.ProfileResponseModel>);
}

/// A class which mocks [ProfileResponseModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileResponseModel extends _i1.Mock
    implements _i2.ProfileResponseModel {
  MockProfileResponseModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  _i2.ProfileUserModel get user =>
      (super.noSuchMethod(
            Invocation.getter(#user),
            returnValue: _FakeProfileUserModel_1(
              this,
              Invocation.getter(#user),
            ),
          )
          as _i2.ProfileUserModel);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i3.ProfileEntity toEntity() =>
      (super.noSuchMethod(
            Invocation.method(#toEntity, []),
            returnValue: _FakeProfileEntity_2(
              this,
              Invocation.method(#toEntity, []),
            ),
          )
          as _i3.ProfileEntity);
}
