// Mocks generated by Mockito 5.4.6 from annotations
// in flowery/test/features/home/presentation/view_model/home_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowery/core/base/base_response.dart' as _i4;
import 'package:flowery/features/home/domian/entities/food_for_you_model.dart'
    as _i5;
import 'package:flowery/features/home/domian/entities/profile_model.dart'
    as _i9;
import 'package:flowery/features/home/domian/entities/recommendation_model.dart'
    as _i8;
import 'package:flowery/features/home/domian/entities/work_out_model.dart'
    as _i7;
import 'package:flowery/features/home/domian/use_case/use_case.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [HomeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeUseCase extends _i1.Mock implements _i2.HomeUseCase {
  MockHomeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.FoodForYouModel>> callFoodData() =>
      (super.noSuchMethod(
            Invocation.method(#callFoodData, []),
            returnValue: _i3.Future<_i4.Result<_i5.FoodForYouModel>>.value(
              _i6.dummyValue<_i4.Result<_i5.FoodForYouModel>>(
                this,
                Invocation.method(#callFoodData, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.FoodForYouModel>>);

  @override
  _i3.Future<_i4.Result<_i7.WorkOutModel>> callWorkOutData() =>
      (super.noSuchMethod(
            Invocation.method(#callWorkOutData, []),
            returnValue: _i3.Future<_i4.Result<_i7.WorkOutModel>>.value(
              _i6.dummyValue<_i4.Result<_i7.WorkOutModel>>(
                this,
                Invocation.method(#callWorkOutData, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i7.WorkOutModel>>);

  @override
  _i3.Future<_i4.Result<_i8.RecommendationModel>> callRecommendationData() =>
      (super.noSuchMethod(
            Invocation.method(#callRecommendationData, []),
            returnValue: _i3.Future<_i4.Result<_i8.RecommendationModel>>.value(
              _i6.dummyValue<_i4.Result<_i8.RecommendationModel>>(
                this,
                Invocation.method(#callRecommendationData, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i8.RecommendationModel>>);

  @override
  _i3.Future<_i4.Result<_i9.ProfileModel>> callProfileData() =>
      (super.noSuchMethod(
            Invocation.method(#callProfileData, []),
            returnValue: _i3.Future<_i4.Result<_i9.ProfileModel>>.value(
              _i6.dummyValue<_i4.Result<_i9.ProfileModel>>(
                this,
                Invocation.method(#callProfileData, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i9.ProfileModel>>);
}
