// Mocks generated by Mockito 5.4.6 from annotations
// in flowery/test/features/popular_training/presentation/view_model/popular_training_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowery/core/base/base_response.dart' as _i5;
import 'package:flowery/features/popular_training/domain/entities/exercise_entity.dart'
    as _i6;
import 'package:flowery/features/popular_training/domain/repository/popular_training_repository_contract.dart'
    as _i2;
import 'package:flowery/features/popular_training/domain/usecase/get_exercises_usecase.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePopularTrainingRepository_0 extends _i1.SmartFake
    implements _i2.PopularTrainingRepository {
  _FakePopularTrainingRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetPopularTrainingUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularTrainingUseCase extends _i1.Mock
    implements _i3.GetPopularTrainingUseCase {
  MockGetPopularTrainingUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PopularTrainingRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePopularTrainingRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PopularTrainingRepository);

  @override
  _i4.Future<_i5.Result<List<_i6.ExerciseEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i5.Result<List<_i6.ExerciseEntity>>>.value(
              _i7.dummyValue<_i5.Result<List<_i6.ExerciseEntity>>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<List<_i6.ExerciseEntity>>>);
}
