// Mocks generated by Mockito 5.4.6 from annotations
// in flowery/test/features/home/data/repository/home_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowery/core/base/base_response.dart' as _i4;
import 'package:flowery/features/home/data/datasourse/home_remote_datasourse_contract.dart'
    as _i2;
import 'package:flowery/features/home/data/models/food_for_you_response_dto.dart'
    as _i5;
import 'package:flowery/features/home/data/models/profile_response_dto.dart'
    as _i9;
import 'package:flowery/features/home/data/models/recommendation_to_day_response_dto.dart'
    as _i8;
import 'package:flowery/features/home/data/models/work_out_response_dto.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [HomeRemoteDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRemoteDataSourceContract extends _i1.Mock
    implements _i2.HomeRemoteDataSourceContract {
  MockHomeRemoteDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.FoodForYouResponseDto>> getFoodData() =>
      (super.noSuchMethod(
            Invocation.method(#getFoodData, []),
            returnValue:
                _i3.Future<_i4.Result<_i5.FoodForYouResponseDto>>.value(
                  _i6.dummyValue<_i4.Result<_i5.FoodForYouResponseDto>>(
                    this,
                    Invocation.method(#getFoodData, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.FoodForYouResponseDto>>);

  @override
  _i3.Future<_i4.Result<_i7.WorkOutResponseDto>> getWorkOutData() =>
      (super.noSuchMethod(
            Invocation.method(#getWorkOutData, []),
            returnValue: _i3.Future<_i4.Result<_i7.WorkOutResponseDto>>.value(
              _i6.dummyValue<_i4.Result<_i7.WorkOutResponseDto>>(
                this,
                Invocation.method(#getWorkOutData, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i7.WorkOutResponseDto>>);

  @override
  _i3.Future<_i4.Result<_i8.RecommendationToDayResponseDto>>
  getRecommendationData() =>
      (super.noSuchMethod(
            Invocation.method(#getRecommendationData, []),
            returnValue:
                _i3.Future<
                  _i4.Result<_i8.RecommendationToDayResponseDto>
                >.value(
                  _i6.dummyValue<
                    _i4.Result<_i8.RecommendationToDayResponseDto>
                  >(this, Invocation.method(#getRecommendationData, [])),
                ),
          )
          as _i3.Future<_i4.Result<_i8.RecommendationToDayResponseDto>>);

  @override
  _i3.Future<_i4.Result<_i9.ProfileResponseDto>> getProfileData() =>
      (super.noSuchMethod(
            Invocation.method(#getProfileData, []),
            returnValue: _i3.Future<_i4.Result<_i9.ProfileResponseDto>>.value(
              _i6.dummyValue<_i4.Result<_i9.ProfileResponseDto>>(
                this,
                Invocation.method(#getProfileData, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i9.ProfileResponseDto>>);
}

/// A class which mocks [FoodForYouResponseDto].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodForYouResponseDto extends _i1.Mock
    implements _i5.FoodForYouResponseDto {
  MockFoodForYouResponseDto() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i5.Category> get categories =>
      (super.noSuchMethod(
            Invocation.getter(#categories),
            returnValue: <_i5.Category>[],
          )
          as List<_i5.Category>);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [WorkOutResponseDto].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkOutResponseDto extends _i1.Mock
    implements _i7.WorkOutResponseDto {
  MockWorkOutResponseDto() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  List<_i7.MuscleGroup> get musclesGroup =>
      (super.noSuchMethod(
            Invocation.getter(#musclesGroup),
            returnValue: <_i7.MuscleGroup>[],
          )
          as List<_i7.MuscleGroup>);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [RecommendationToDayResponseDto].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecommendationToDayResponseDto extends _i1.Mock
    implements _i8.RecommendationToDayResponseDto {
  MockRecommendationToDayResponseDto() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  int get totalMuscles =>
      (super.noSuchMethod(Invocation.getter(#totalMuscles), returnValue: 0)
          as int);

  @override
  List<_i8.Muscle> get muscles =>
      (super.noSuchMethod(
            Invocation.getter(#muscles),
            returnValue: <_i8.Muscle>[],
          )
          as List<_i8.Muscle>);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
