// Mocks generated by Mockito 5.4.6 from annotations
// in flowery/test/feature/profile/presentation/view/screen/profile_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flowery/feature/logout/presentation/veiw_model.dart/logout_cubit.dart'
    as _i8;
import 'package:flowery/feature/logout/presentation/veiw_model.dart/logout_event.dart'
    as _i9;
import 'package:flowery/feature/logout/presentation/veiw_model.dart/logout_state.dart'
    as _i3;
import 'package:flowery/feature/profile/domain/entities/profile_entity.dart'
    as _i10;
import 'package:flowery/feature/profile/presentation/view_model/profile_cubit.dart'
    as _i4;
import 'package:flowery/feature/profile/presentation/view_model/profile_event.dart'
    as _i6;
import 'package:flowery/feature/profile/presentation/view_model/profile_state.dart'
    as _i2;
import 'package:flutter_bloc/flutter_bloc.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProfileStates_0 extends _i1.SmartFake implements _i2.ProfileStates {
  _FakeProfileStates_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogoutStates_1 extends _i1.SmartFake implements _i3.LogoutStates {
  _FakeLogoutStates_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileCubit extends _i1.Mock implements _i4.ProfileCubit {
  MockProfileCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileStates get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeProfileStates_0(this, Invocation.getter(#state)),
          )
          as _i2.ProfileStates);

  @override
  _i5.Stream<_i2.ProfileStates> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i2.ProfileStates>.empty(),
          )
          as _i5.Stream<_i2.ProfileStates>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void doAction(_i6.ProfileEvents? event) => super.noSuchMethod(
    Invocation.method(#doAction, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i2.ProfileStates? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i7.Change<_i2.ProfileStates>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [LogoutCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutCubit extends _i1.Mock implements _i8.LogoutCubit {
  MockLogoutCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.LogoutStates get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeLogoutStates_1(this, Invocation.getter(#state)),
          )
          as _i3.LogoutStates);

  @override
  _i5.Stream<_i3.LogoutStates> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i3.LogoutStates>.empty(),
          )
          as _i5.Stream<_i3.LogoutStates>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void doAction(_i9.LogoutEvents? event) => super.noSuchMethod(
    Invocation.method(#doAction, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.LogoutStates? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i7.Change<_i3.LogoutStates>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ProfileEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileEntity extends _i1.Mock implements _i10.ProfileEntity {
  MockProfileEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i11.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get firstName =>
      (super.noSuchMethod(
            Invocation.getter(#firstName),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#firstName),
            ),
          )
          as String);

  @override
  String get lastName =>
      (super.noSuchMethod(
            Invocation.getter(#lastName),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#lastName),
            ),
          )
          as String);

  @override
  String get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);
}
