// Mocks generated by Mockito 5.4.6 from annotations
// in flowery/test/features/home/api/datasourse/home_remote_datasourse_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flowery/features/home/api/api_client/home_api_client.dart'
    as _i6;
import 'package:flowery/features/home/data/models/food_for_you_response_dto.dart'
    as _i4;
import 'package:flowery/features/home/data/models/profile_response_dto.dart'
    as _i5;
import 'package:flowery/features/home/data/models/recommendation_to_day_response_dto.dart'
    as _i2;
import 'package:flowery/features/home/data/models/work_out_response_dto.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRecommendationToDayResponseDto_0 extends _i1.SmartFake
    implements _i2.RecommendationToDayResponseDto {
  _FakeRecommendationToDayResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeWorkOutResponseDto_1 extends _i1.SmartFake
    implements _i3.WorkOutResponseDto {
  _FakeWorkOutResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFoodForYouResponseDto_2 extends _i1.SmartFake
    implements _i4.FoodForYouResponseDto {
  _FakeFoodForYouResponseDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileResponseDto_3 extends _i1.SmartFake
    implements _i5.ProfileResponseDto {
  _FakeProfileResponseDto_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserDto_4 extends _i1.SmartFake implements _i5.UserDto {
  _FakeUserDto_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeApiClient extends _i1.Mock implements _i6.HomeApiClient {
  MockHomeApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.RecommendationToDayResponseDto> getRecommendationData() =>
      (super.noSuchMethod(
            Invocation.method(#getRecommendationData, []),
            returnValue: _i7.Future<_i2.RecommendationToDayResponseDto>.value(
              _FakeRecommendationToDayResponseDto_0(
                this,
                Invocation.method(#getRecommendationData, []),
              ),
            ),
          )
          as _i7.Future<_i2.RecommendationToDayResponseDto>);

  @override
  _i7.Future<_i3.WorkOutResponseDto> getWorkOutData() =>
      (super.noSuchMethod(
            Invocation.method(#getWorkOutData, []),
            returnValue: _i7.Future<_i3.WorkOutResponseDto>.value(
              _FakeWorkOutResponseDto_1(
                this,
                Invocation.method(#getWorkOutData, []),
              ),
            ),
          )
          as _i7.Future<_i3.WorkOutResponseDto>);

  @override
  _i7.Future<_i4.FoodForYouResponseDto> getFoodData() =>
      (super.noSuchMethod(
            Invocation.method(#getFoodData, []),
            returnValue: _i7.Future<_i4.FoodForYouResponseDto>.value(
              _FakeFoodForYouResponseDto_2(
                this,
                Invocation.method(#getFoodData, []),
              ),
            ),
          )
          as _i7.Future<_i4.FoodForYouResponseDto>);

  @override
  _i7.Future<_i5.ProfileResponseDto> getProfileData() =>
      (super.noSuchMethod(
            Invocation.method(#getProfileData, []),
            returnValue: _i7.Future<_i5.ProfileResponseDto>.value(
              _FakeProfileResponseDto_3(
                this,
                Invocation.method(#getProfileData, []),
              ),
            ),
          )
          as _i7.Future<_i5.ProfileResponseDto>);
}

/// A class which mocks [FoodForYouResponseDto].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodForYouResponseDto extends _i1.Mock
    implements _i4.FoodForYouResponseDto {
  MockFoodForYouResponseDto() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.Category> get categories =>
      (super.noSuchMethod(
            Invocation.getter(#categories),
            returnValue: <_i4.Category>[],
          )
          as List<_i4.Category>);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [WorkOutResponseDto].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkOutResponseDto extends _i1.Mock
    implements _i3.WorkOutResponseDto {
  MockWorkOutResponseDto() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  List<_i3.MuscleGroup> get musclesGroup =>
      (super.noSuchMethod(
            Invocation.getter(#musclesGroup),
            returnValue: <_i3.MuscleGroup>[],
          )
          as List<_i3.MuscleGroup>);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [RecommendationToDayResponseDto].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecommendationToDayResponseDto extends _i1.Mock
    implements _i2.RecommendationToDayResponseDto {
  MockRecommendationToDayResponseDto() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  int get totalMuscles =>
      (super.noSuchMethod(Invocation.getter(#totalMuscles), returnValue: 0)
          as int);

  @override
  List<_i2.Muscle> get muscles =>
      (super.noSuchMethod(
            Invocation.getter(#muscles),
            returnValue: <_i2.Muscle>[],
          )
          as List<_i2.Muscle>);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [ProfileResponseDto].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileResponseDto extends _i1.Mock
    implements _i5.ProfileResponseDto {
  MockProfileResponseDto() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  _i5.UserDto get user =>
      (super.noSuchMethod(
            Invocation.getter(#user),
            returnValue: _FakeUserDto_4(this, Invocation.getter(#user)),
          )
          as _i5.UserDto);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
