// Mocks generated by Mockito 5.4.6 from annotations
// in flowery/test/features/popular_training/api/datasource/popular_training_datasource_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flowery/features/popular_training/api/api_client/popular_training_api_client.dart'
    as _i5;
import 'package:flowery/features/popular_training/data/models/exercise_model_reponse.dart'
    as _i4;
import 'package:flowery/features/popular_training/data/models/level_model_response.dart'
    as _i3;
import 'package:flowery/features/popular_training/data/models/muscle_model_response.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMusclesResponse_0 extends _i1.SmartFake
    implements _i2.MusclesResponse {
  _FakeMusclesResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLevelsResponse_1 extends _i1.SmartFake
    implements _i3.LevelsResponse {
  _FakeLevelsResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExercisesResponse_2 extends _i1.SmartFake
    implements _i4.ExercisesResponse {
  _FakeExercisesResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PopularTrainingApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularTrainingApiClient extends _i1.Mock
    implements _i5.PopularTrainingApiClient {
  MockPopularTrainingApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.MusclesResponse> getRandomPrimeMoverMuscles() =>
      (super.noSuchMethod(
            Invocation.method(#getRandomPrimeMoverMuscles, []),
            returnValue: _i6.Future<_i2.MusclesResponse>.value(
              _FakeMusclesResponse_0(
                this,
                Invocation.method(#getRandomPrimeMoverMuscles, []),
              ),
            ),
          )
          as _i6.Future<_i2.MusclesResponse>);

  @override
  _i6.Future<_i3.LevelsResponse> getLevels() =>
      (super.noSuchMethod(
            Invocation.method(#getLevels, []),
            returnValue: _i6.Future<_i3.LevelsResponse>.value(
              _FakeLevelsResponse_1(this, Invocation.method(#getLevels, [])),
            ),
          )
          as _i6.Future<_i3.LevelsResponse>);

  @override
  _i6.Future<_i4.ExercisesResponse> getExercises({
    required String? primeMoverMuscleId,
    required String? difficultyLevelId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExercises, [], {
              #primeMoverMuscleId: primeMoverMuscleId,
              #difficultyLevelId: difficultyLevelId,
            }),
            returnValue: _i6.Future<_i4.ExercisesResponse>.value(
              _FakeExercisesResponse_2(
                this,
                Invocation.method(#getExercises, [], {
                  #primeMoverMuscleId: primeMoverMuscleId,
                  #difficultyLevelId: difficultyLevelId,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.ExercisesResponse>);
}
