// Mocks generated by Mockito 5.4.6 from annotations
// in flowery/test/features/register/presentation/view_model/register_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowery/core/base/base_response.dart' as _i4;
import 'package:flowery/features/register/domain/entities/register_model.dart'
    as _i5;
import 'package:flowery/features/register/domain/use_cases/register_usecase.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [RegisterUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUsecase extends _i1.Mock implements _i2.RegisterUsecase {
  MockRegisterUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.RegisterModel>> invoke(
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#invoke, [body]),
            returnValue: _i3.Future<_i4.Result<_i5.RegisterModel>>.value(
              _i6.dummyValue<_i4.Result<_i5.RegisterModel>>(
                this,
                Invocation.method(#invoke, [body]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.RegisterModel>>);
}
